import Config

# Configure your database
config :youtube_summarizer, YoutubeSummarizer.Repo,
  username: "postgres",
  password: "root",
  hostname: "localhost",
  database: "youtube_summarizer_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :youtube_summarizer, YoutubeSummarizerWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "LgtbM/UmqyQuugvYsDvWksBSc5SJ/tx5nCvHd2YBzLQA+hCPpWJVjkk09Xrf+eOF",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:youtube_summarizer, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:youtube_summarizer, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :youtube_summarizer, YoutubeSummarizerWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/youtube_summarizer_web/(controllers|live|components)/.*(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :youtube_summarizer, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

config :logger, level: :debug

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include HEEx debug annotations as HTML comments in rendered markup
  debug_heex_annotations: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# Load environment variables
youtube_api_key = System.get_env("YOUTUBE_API_KEY")
anthropic_api_key = System.get_env("ANTHROPIC_API_KEY")

if is_nil(youtube_api_key) do
  raise "YouTube API key is not set in the environment"
end

if is_nil(anthropic_api_key) do
  raise "Anthropic API key is not set in the environment"
end


config :youtube_summarizer,
  youtube_client_id: System.get_env("YOUTUBE_CLIENT_ID"),
  youtube_client_secret: System.get_env("YOUTUBE_CLIENT_SECRET"),
  youtube_redirect_uri: "http://localhost:4000/auth/youtube/callback"

# Print API keys for debugging (remove in production)
IO.puts "YouTube API Key: #{youtube_api_key}"
IO.puts "Anthropic API Key: #{anthropic_api_key}"
